# Generated by Django 4.1.7 on 2023-05-28 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('time_limit', models.DurationField(default=datetime.timedelta(seconds=60))),
                ('award', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('options', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
