# Generated by Django 4.1.7 on 2023-05-28 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userrules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRules',
            new_name='UserRule',
        ),
    ]
