# Generated by Django 4.1.7 on 2023-05-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_userrules_userrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField(blank=True, null=True)),
                ('score', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
